PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://purl.org/stuff/transmissions/>

# https://schema.org/BlogPosting
# https://schema.org/Article

INSERT DATA {
  <http://danny.ayers.name/me> a schema:Person ;
      schema:name "Danny" .
  <http:/danny.ayers.name/blog/----- ENTRIES ----/home/danny/sites/danny,ayers,name/postcraft/content-raw/markor-docs/----- EN/2025-01-03_elfquake> a schema:Article ;
    :sourcePath "/home/danny/sites/danny.ayers.name/postcraft/content-raw/markor-docs/----- ENTRIES ----/2025-01-03_elfquake.md" ;
    :relPath "----- ENTRIES ----/home/danny/sites/danny,ayers,name/postcraft/content-raw/markor-docs/----- EN" ;
    :slug "2025-01-03_elfquake" ;
    schema:headline "ELFQuake" ;
    schema:datePublished "/home/danny/sites/danny,ayers,name/postcraft/content-raw/markor-docs/----- ENTRIES ----/2025-01-03"^^xsd:dateTime ;
    schema:dateModified "2025-02-15T13:50:07"^^xsd:dateTime ;
    schema:creator <http://danny.ayers.name/me> ;
    schema:articleBody """# ELFQuake

This is the earthquake prediction project I&#39;ve been working on. Info on that below, but first -

## Radio 4

[Jim Al-Khalili](https://en.wikipedia.org/wiki/Jim_Al-Khalili)&#39;s (very listenable) scientist-biography series &quot;The Life Scientific&quot; has [this episode](https://www.bbc.co.uk/sounds/play/m001k7tt) featuring geophysicist [James Jackson](https://en.wikipedia.org/wiki/James_Jackson_%28geophysicist%29). It&#39;s a great backgrounder on the seismo field. I got many important takeaways.

One was around popular perceptions. He made the point that (at the time of the broadcast at least) it had to be stressed that short-term prediction isn&#39;t possible. He referred to the social fallout from the [2009 L&#39;Aquila earthquake](https://en.wikipedia.org/wiki/2009_L%27Aquila_earthquake) (See also, below). A group of scientists were convicted of involuntary manslaughter for not predicting the quake (I&#39;m paraphrasing, the Wikipedia article has more of the full story). Jackson&#39;s stance on this is well justified, this is another problem (like climate change) with an aura of **&quot;science will solve it&quot;** which can lead to a **lack of necessary, immediately doable**, action.

 In contrast, Jackson mentions the [April 2015 Nepal earthquake](https://en.wikipedia.org/wiki/April_2015_Nepal_earthquake) (7.8 [Mw](https://en.wikipedia.org/wiki/Moment_magnitude_scale) - he attended a conference on prep there **two weeks before the quake** . A Nepalese guy (name?) behind an NGO that had built 300 (?) schools according to best known practices. All still standing after the event and used as emergency centres, while 800 (?) other schools where destroyed.

At a slight tangent, coincidentally this morning I saw a post by Steven Pemberton on [Facebook](https://www.facebook.com/share/12Cke36ivdW/)

Y2K was 25 years ago. The Guardian has an article describing it as a &quot;damp squib&quot;, as if they&#39;d have rather something go disastrously wrong...

The message: if a lot of people work for a decade to prevent a problem from happening, others will conclude it wasn&#39;t really a problem.

In comments there

## ELFQuake

""" .

}
